#!/usr/bin/env node
// ============================================================
// devkit-cli — Command-line developer toolkit for scaffolding projects
// Usage: node src/cli.js <command> [options]
// ============================================================

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const VERSION = '1.0.0';
const CWD = process.cwd();

const HELP_TEXT = `
┌─────────────────────────────────────────────────────┐
│  devkit-cli v${VERSION} — Developer Project Scaffolding Tool  │
└─────────────────────────────────────────────────────┘

Usage:
  node src/cli.js <command> [options]

Commands:
  new <name> [options]   Scaffold a new project
  list                   List available templates
  info <template>        Show template details

New Project Options:
  --lang, -l <lang>      Language: node | python | go (default: node)
  --template, -t <name>  Template: basic | cli | api | lib (default: basic)
  --git, -g              Initialize git repository
  --install, -i          Install dependencies after scaffold

Examples:
  node src/cli.js new my-api --lang node --template api
  node src/cli.js new my-tool --lang python --template cli
  node src/cli.js list
  node src/cli.js info node-api

  npx devkit-cli new awesome-project
`;

// ─── Templates ────────────────────────────────────────────

const TEMPLATES = {
  node: {
    basic: {
      description: 'Minimal Node.js project with package.json',
      files: {
        'package.json': (name) => JSON.stringify({
          name,
          version: '1.0.0',
          description: '',
          main: 'index.js',
          scripts: { start: 'node index.js', test: 'echo "No tests yet"' },
          keywords: [],
          author: '',
          license: 'MIT'
        }, null, 2),
        'index.js': `// Entry point for ${name}
console.log('Hello from ${name}!');\n`,
        '.gitignore': 'node_modules/\n.env\n*.log\n',
        'README.md': (name) => `# ${name}\n\nGenerated by devkit-cli.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`
      }
    },
    cli: {
      description: 'Node.js CLI tool with argument parsing',
      files: {
        'package.json': (name) => JSON.stringify({
          name,
          version: '1.0.0',
          bin: { [name]: 'bin/cli.js' },
          main: 'index.js',
          scripts: { start: 'node bin/cli.js', test: 'echo "No tests yet"' },
          license: 'MIT'
        }, null, 2),
        'bin/cli.js': `#!/usr/bin/env node
const args = process.argv.slice(2);
console.log('${name} CLI');
console.log('Arguments:', args);\n`,
        'index.js': `module.exports = { hello: () => 'Hello from ${name}' };\n`,
        '.gitignore': 'node_modules/\n.env\n*.log\n',
        'README.md': (name) => `# ${name}\n\nCLI tool generated by devkit-cli.\n\n## Usage\n\n\`\`\`bash\nnpx ${name} --help\n\`\`\`\n`
      }
    },
    api: {
      description: 'Node.js Express REST API',
      files: {
        'package.json': (name) => JSON.stringify({
          name,
          version: '1.0.0',
          main: 'server.js',
          scripts: {
            start: 'node server.js',
            dev: 'nodemon server.js',
            test: 'echo "Add tests"'
          },
          dependencies: { express: '^4.18.0' },
          devDependencies: { nodemon: '^3.0.0' },
          license: 'MIT'
        }, null, 2),
        'server.js': `const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: '${name} API is running' });
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});\n`,
        '.env.example': 'PORT=3000\nDATABASE_URL=\n',
        '.gitignore': 'node_modules/\n.env\n*.log\n',
        'README.md': (name) => `# ${name}\n\nExpress API generated by devkit-cli.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Endpoints\n\n- GET / - API info\n- GET /health - Health check\n`
      }
    },
    lib: {
      description: 'Node.js library with test scaffolding',
      files: {
        'package.json': (name) => JSON.stringify({
          name,
          version: '1.0.0',
          main: 'lib/index.js',
          scripts: {
            test: 'node test/index.test.js',
            lint: 'eslint lib/'
          },
          license: 'MIT'
        }, null, 2),
        'lib/index.js': `function greet(name = 'World') {
  return \`Hello, \${name}!\`;
}

module.exports = { greet };\n`,
        'test/index.test.js': `const { greet } = require('../lib/index');

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    console.error(\`FAIL: \${message}\`);
    console.error(\`  Expected: \${expected}\`);
    console.error(\`  Actual: \${actual}\`);
    process.exit(1);
  }
  console.log(\`PASS: \${message}\`);
}

assertEqual(greet(), 'Hello, World!', 'greet with no args');
assertEqual(greet('Dev'), 'Hello, Dev!', 'greet with name');
console.log('All tests passed!');\n`,
        '.gitignore': 'node_modules/\n.env\n*.log\n',
        'README.md': (name) => `# ${name}\n\nLibrary generated by devkit-cli.\n\n## Usage\n\n\`\`\`js\nconst { greet } = require('${name}');\nconsole.log(greet('Developer'));\n\`\`\`\n`
      }
    }
  },
  python: {
    basic: {
      description: 'Minimal Python project',
      files: {
        'main.py': `# Entry point for ${name}
def main():
    print(f"Hello from ${name}!")

if __name__ == "__main__":
    main()
`,
        'requirements.txt': '# Add your dependencies here\n',
        '.gitignore': '__pycache__/\n*.pyc\n.env\nvenv/\n',
        'README.md': (name) => `# ${name}\n\nPython project generated by devkit-cli.\n\n## Getting Started\n\n\`\`\`bash\npip install -r requirements.txt\npython main.py\n\`\`\`\n`
      }
    },
    cli: {
      description: 'Python CLI with argparse',
      files: {
        'main.py': `import argparse

def main():
    parser = argparse.ArgumentParser(description='${name} CLI')
    parser.add_argument('--name', default='World', help='Name to greet')
    args = parser.parse_args()
    print(f"Hello, {args.name}!")

if __name__ == "__main__":
    main()
`,
        'requirements.txt': '# Add your dependencies here\n',
        '.gitignore': '__pycache__/\n*.pyc\n.env\nvenv/\n',
        'README.md': (name) => `# ${name}\n\nPython CLI generated by devkit-cli.\n\n## Usage\n\n\`\`\`bash\npython main.py --name Developer\n\`\`\`\n`
      }
    },
    api: {
      description: 'Python Flask REST API',
      files: {
        'app.py': `from flask import Flask, jsonify
from datetime import datetime

app = Flask(__name__)

@app.route('/')
def home():
    return jsonify({"message": "${name} API is running"})

@app.route('/health')
def health():
    return jsonify({"status": "ok", "timestamp": datetime.now().isoformat()})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
`,
        'requirements.txt': 'flask\n',
        '.env.example': 'FLASK_ENV=development\nPORT=5000\n',
        '.gitignore': '__pycache__/\n*.pyc\n.env\nvenv/\n',
        'README.md': (name) => `# ${name}\n\nFlask API generated by devkit-cli.\n\n## Setup\n\n\`\`\`bash\npip install -r requirements.txt\npython app.py\n\`\`\`\n\n## Endpoints\n\n- GET / - API info\n- GET /health - Health check\n`
      }
    },
    lib: {
      description: 'Python library with test scaffolding',
      files: {
        f'{name}/__init__.py': `def greet(name="World"):
    return f"Hello, {name}!"
`,
        'tests/test_greet.py': `import sys
sys.path.insert(0, '.')
from ${name} import greet

def test_greet_default():
    assert greet() == "Hello, World!"

def test_greet_name():
    assert greet("Dev") == "Hello, Dev!"

if __name__ == "__main__":
    test_greet_default()
    test_greet_name()
    print("All tests passed!")
`,
        'setup.py': `from setuptools import setup, find_packages

setup(
    name='${name}',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[],
    python_requires='>=3.8',
)
`,
        '.gitignore': '__pycache__/\n*.pyc\n.env\nvenv/\nbuild/\ndist/\n*.egg-info/\n',
        'README.md': (name) => `# ${name}\n\nPython library generated by devkit-cli.\n\n## Usage\n\n\`\`\`python\nfrom ${name} import greet\nprint(greet("Developer"))\n\`\`\`\n`
      }
    }
  },
  go: {
    basic: {
      description: 'Minimal Go project',
      files: {
        'main.go': `package main

import "fmt"

func main() {
	fmt.Println("Hello from ${name}!")
}
`,
        'go.mod': `module ${name}

go 1.21
`,
        '.gitignore': '*.exe\n*.out\n*.test\n/vendor/\n',
        'README.md': (name) => `# ${name}\n\nGo project generated by devkit-cli.\n\n## Getting Started\n\n\`\`\`bash\ngo run main.go\n\`\`\`\n`
      }
    },
    cli: {
      description: 'Go CLI with flag parsing',
      files: {
        'main.go': `package main

import (
	"flag"
	"fmt"
)

func main() {
	name := flag.String("name", "World", "Name to greet")
	flag.Parse()
	fmt.Printf("Hello, %s!\\n", *name)
}
`,
        'go.mod': `module ${name}

go 1.21
`,
        '.gitignore': '*.exe\n*.out\n*.test\n/vendor/\n',
        'README.md': (name) => `# ${name}\n\nGo CLI generated by devkit-cli.\n\n## Usage\n\n\`\`\`bash\ngo run main.go -name Developer\n\`\`\`\n`
      }
    },
    api: {
      description: 'Go HTTP API with net/http',
      files: {
        'main.go': `package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]string{
			"message": "${name} API is running",
		})
	})

	http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]interface{}{
			"status":    "ok",
			"timestamp": time.Now().Format(time.RFC3339),
		})
	})

	fmt.Println("Server running on :8080")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
`,
        'go.mod': `module ${name}

go 1.21
`,
        '.env.example': 'PORT=8080\n',
        '.gitignore': '*.exe\n*.out\n*.test\n/vendor/\n',
        'README.md': (name) => `# ${name}\n\nGo API generated by devkit-cli.\n\n## Run\n\n\`\`\`bash\ngo run main.go\n\`\`\`\n\n## Endpoints\n\n- GET / - API info\n- GET /health - Health check\n`
      }
    },
    lib: {
      description: 'Go library with test scaffolding',
      files: {
        f'{name}.go': `package ${name}

import "fmt"

func Greet(name string) string {
	if name == "" {
		name = "World"
	}
	return fmt.Sprintf("Hello, %s!", name)
}
`,
        f'{name}_test.go': `package ${name}

import "testing"

func TestGreet(t *testing.T) {
	if Greet("") != "Hello, World!" {
		t.Error("Default greeting failed")
	}
	if Greet("Dev") != "Hello, Dev!" {
		t.Error("Named greeting failed")
	}
}
`,
        'go.mod': `module ${name}

go 1.21
`,
        '.gitignore': '*.exe\n*.out\n*.test\n/vendor/\n',
        'README.md': (name) => `# ${name}\n\nGo library generated by devkit-cli.\n\n## Usage\n\n\`\`\`go\nimport "${name}"\nfmt.Println(${name}.Greet("Developer"))\n\`\`\`\n`
      }
    }
  }
};

// ─── CLI Parser ───────────────────────────────────────────

function parseArgs(args) {
  const result = { command: '', name: '', options: {} };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (i === 0 && !arg.startsWith('-')) result.command = arg;
    else if (result.command && !result.name && !arg.startsWith('-')) result.name = arg;
    else if (['--lang', '-l'].includes(arg)) result.options.lang = args[++i] || 'node';
    else if (['--template', '-t'].includes(arg)) result.options.template = args[++i] || 'basic';
    else if (['--git', '-g'].includes(arg)) result.options.git = true;
    else if (['--install', '-i'].includes(arg)) result.options.install = true;
  }
  return result;
}

// ─── Scaffolder ───────────────────────────────────────────

function createDirectory(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`  mkdir: ${path.relative(CWD, dir)}`);
  }
}

function writeFile(filePath, content) {
  const dir = path.dirname(filePath);
  createDirectory(dir);
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`  write: ${path.relative(CWD, filePath)}`);
}

function scaffoldProject(name, lang, templateKey, options) {
  const template = TEMPLATES[lang]?.[templateKey];
  if (!template) {
    console.error(`\nError: Template "${lang}/${templateKey}" not found.`);
    console.log(`Run \`node src/cli.js list\` to see available templates.\n`);
    process.exit(1);
  }

  const projectDir = path.join(CWD, name);
  if (fs.existsSync(projectDir)) {
    console.error(`\nError: Directory "${name}" already exists.\n`);
    process.exit(1);
  }

  console.log(`\nScaffolding "${name}" (${lang}/${templateKey})...\n`);
  createDirectory(projectDir);

  // Write template files
  for (const [filePath, content] of Object.entries(template.files)) {
    let resolvedPath = filePath;
    if (filePath.startsWith('{name}')) {
      resolvedPath = filePath.replace('{name}', name);
    }
    const fullPath = path.join(projectDir, resolvedPath);
    const fileContent = typeof content === 'function' ? content(name) : content;
    writeFile(fullPath, fileContent);
  }

  // Git init
  if (options.git) {
    console.log('\n  git init...');
    try {
      execSync('git init', { cwd: projectDir, stdio: 'ignore' });
      execSync('git add .', { cwd: projectDir, stdio: 'ignore' });
      execSync('git commit -m "Initial commit"', { cwd: projectDir, stdio: 'ignore' });
      console.log('  Repository initialized.');
    } catch {
      console.log('  Git init skipped (git not available).');
    }
  }

  // Install dependencies
  if (options.install) {
    console.log(`\n  Installing dependencies for ${lang}...`);
    try {
      if (lang === 'node') execSync('npm install', { cwd: projectDir, stdio: 'inherit' });
      else if (lang === 'python') execSync('pip install -r requirements.txt', { cwd: projectDir, stdio: 'inherit' });
      else if (lang === 'go') execSync('go mod tidy', { cwd: projectDir, stdio: 'inherit' });
    } catch {
      console.log('  Install skipped (package manager not available).');
    }
  }

  console.log(`\nDone! Your project is ready at: ${projectDir}\n`);
  console.log(`  cd ${name}`);
  if (lang === 'node') console.log('  npm start');
  else if (lang === 'python') console.log('  python main.py');
  else if (lang === 'go') console.log('  go run main.go');
  console.log('');
}

// ─── List & Info ──────────────────────────────────────────

function listTemplates() {
  console.log('\nAvailable Templates\n' + '='.repeat(40));
  for (const [lang, templates] of Object.entries(TEMPLATES)) {
    console.log(`\n${lang.toUpperCase()}`);
    for (const [key, tmpl] of Object.entries(templates)) {
      console.log(`  ${lang}-${key.padEnd(12)} ${tmpl.description}`);
    }
  }
  console.log('');
}

function showInfo(templateName) {
  const [lang, templateKey] = templateName.split('-');
  const template = TEMPLATES[lang]?.[templateKey];
  if (!template) {
    console.error(`\nTemplate "${templateName}" not found.\n`);
    process.exit(1);
  }
  console.log(`\nTemplate: ${templateName}`);
  console.log(`Description: ${template.description}`);
  console.log('Files:');
  for (const filePath of Object.keys(template.files)) {
    console.log(`  - ${filePath}`);
  }
  console.log('');
}

// ─── Main ─────────────────────────────────────────────────

function main() {
  const args = parseArgs(process.argv.slice(2));

  if (!args.command || args.command === 'help' || args.command === '--help' || args.command === '-h') {
    console.log(HELP_TEXT);
    process.exit(0);
  }

  if (args.command === 'version' || args.command === '--version' || args.command === '-v') {
    console.log(VERSION);
    process.exit(0);
  }

  if (args.command === 'list') {
    listTemplates();
    process.exit(0);
  }

  if (args.command === 'info') {
    if (!args.name) {
      console.error('Usage: node src/cli.js info <template-name>');
      process.exit(1);
    }
    showInfo(args.name);
    process.exit(0);
  }

  if (args.command === 'new') {
    if (!args.name) {
      console.error('\nError: Project name is required.\n');
      console.log('Usage: node src/cli.js new <name> [options]\n');
      process.exit(1);
    }
    const lang = args.options.lang || 'node';
    const templateKey = args.options.template || 'basic';
    scaffoldProject(args.name, lang, templateKey, args.options);
    process.exit(0);
  }

  console.error(`\nUnknown command: "${args.command}"`);
  console.log('Run \`node src/cli.js --help\` for usage.\n');
  process.exit(1);
}

main();
